DATA:
  data_path: None
MODEL:
  model_name: model_weights.pth
VAL:
  validation: True
  val_batch_size: 1
  val_patience: 2
OPTIMIZATION:
  learning_rate: 0.001
  batch_size: 64
  sche_decay_factor: 0.5
  sche_patience: 6
  sche_threshold: 0.001
  num_epochs: 10
EVALUATION:
  plot: False